function Hd = filter_electrical_noise
%FILTER_ELECTRICAL_NOISE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 17-Mar-2024 19:50:41

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 125;  % Sampling Frequency

N   = 10;  % Order
Fc1 = 59;  % First Cutoff Frequency
Fc2 = 61;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
