function Hd = chebyshev_t2_EOG_blink
%CHEBYSHEV_T2_EOG_BLINK Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 02-Apr-2024 21:17:50

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

Fstop1 = 1.25;        % First Stopband Frequency
Fpass1 = 1.5;         % First Passband Frequency
Fpass2 = 8;           % Second Passband Frequency
Fstop2 = 8.25;        % Second Stopband Frequency
Astop1 = 40;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 40;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
end